[2025-06-25T01:58:44.617+0200] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: order_monitoring_dag16.run_dbt_models manual__2025-06-24T23:58:33.725867+00:00 [queued]>
[2025-06-25T01:58:44.632+0200] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: order_monitoring_dag16.run_dbt_models manual__2025-06-24T23:58:33.725867+00:00 [queued]>
[2025-06-25T01:58:44.632+0200] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2025-06-25T01:58:44.706+0200] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): run_dbt_models> on 2025-06-24 23:58:33.725867+00:00
[2025-06-25T01:58:44.712+0200] {standard_task_runner.py:57} INFO - Started process 192082 to run task
[2025-06-25T01:58:44.743+0200] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'order_monitoring_dag16', 'run_dbt_models', 'manual__2025-06-24T23:58:33.725867+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/order_monitoring_dag.py', '--cfg-path', '/tmp/tmpja84ojvy']
[2025-06-25T01:58:44.752+0200] {standard_task_runner.py:85} INFO - Job 14: Subtask run_dbt_models
[2025-06-25T01:58:44.941+0200] {task_command.py:410} INFO - Running <TaskInstance: order_monitoring_dag16.run_dbt_models manual__2025-06-24T23:58:33.725867+00:00 [running]> on host 192.168.152.131
[2025-06-25T01:58:45.121+0200] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='imamzafar100@gmail.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='order_monitoring_dag16' AIRFLOW_CTX_TASK_ID='run_dbt_models' AIRFLOW_CTX_EXECUTION_DATE='2025-06-24T23:58:33.725867+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-24T23:58:33.725867+00:00'
[2025-06-25T01:58:45.129+0200] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2025-06-25T01:58:45.139+0200] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'source "/home/atef/dbt_env/bin/activate" && cd "/home/atef/project/E-Commerce-Order-Pipeline/dbt_ecommerce" && dbt run']
[2025-06-25T01:58:45.230+0200] {subprocess.py:86} INFO - Output:
[2025-06-25T01:58:53.916+0200] {subprocess.py:93} INFO - /home/atef/dbt_env/lib64/python3.9/site-packages/networkx/utils/backends.py:135: RuntimeWarning: networkx backend defined more than once: nx-loopback
[2025-06-25T01:58:53.918+0200] {subprocess.py:93} INFO -   backends.update(_get_backends("networkx.backends"))
[2025-06-25T01:58:55.106+0200] {subprocess.py:93} INFO - [0m23:58:55  Running with dbt=1.10.2
[2025-06-25T01:58:57.375+0200] {subprocess.py:93} INFO - [0m23:58:57  Registered adapter: snowflake=1.9.4
[2025-06-25T01:58:59.565+0200] {subprocess.py:93} INFO - [0m23:58:59  Found 4 models, 476 macros
[2025-06-25T01:58:59.571+0200] {subprocess.py:93} INFO - [0m23:58:59
[2025-06-25T01:58:59.573+0200] {subprocess.py:93} INFO - [0m23:58:59  Concurrency: 1 threads (target='dev')
[2025-06-25T01:58:59.575+0200] {subprocess.py:93} INFO - [0m23:58:59
[2025-06-25T01:59:02.793+0200] {subprocess.py:93} INFO - [0m23:59:02  1 of 4 START sql view model ANALYTICS.stg_customers ............................ [RUN]
[2025-06-25T01:59:03.587+0200] {subprocess.py:93} INFO - [0m23:59:03  1 of 4 OK created sql view model ANALYTICS.stg_customers ....................... [[32mSUCCESS 1[0m in 0.79s]
[2025-06-25T01:59:03.593+0200] {subprocess.py:93} INFO - [0m23:59:03  2 of 4 START sql view model ANALYTICS.stg_orders ............................... [RUN]
[2025-06-25T01:59:03.914+0200] {subprocess.py:93} INFO - [0m23:59:03  2 of 4 OK created sql view model ANALYTICS.stg_orders .......................... [[32mSUCCESS 1[0m in 0.32s]
[2025-06-25T01:59:03.920+0200] {subprocess.py:93} INFO - [0m23:59:03  3 of 4 START sql view model ANALYTICS.stg_shipments ............................ [RUN]
[2025-06-25T01:59:04.301+0200] {subprocess.py:93} INFO - [0m23:59:04  3 of 4 OK created sql view model ANALYTICS.stg_shipments ....................... [[32mSUCCESS 1[0m in 0.38s]
[2025-06-25T01:59:04.310+0200] {subprocess.py:93} INFO - [0m23:59:04  4 of 4 START sql view model ANALYTICS.order_status ............................. [RUN]
[2025-06-25T01:59:04.852+0200] {subprocess.py:93} INFO - [0m23:59:04  4 of 4 OK created sql view model ANALYTICS.order_status ........................ [[32mSUCCESS 1[0m in 0.54s]
[2025-06-25T01:59:05.581+0200] {subprocess.py:93} INFO - [0m23:59:05
[2025-06-25T01:59:05.584+0200] {subprocess.py:93} INFO - [0m23:59:05  Finished running 4 view models in 0 hours 0 minutes and 6.00 seconds (6.00s).
[2025-06-25T01:59:05.731+0200] {subprocess.py:93} INFO - [0m23:59:05
[2025-06-25T01:59:05.733+0200] {subprocess.py:93} INFO - [0m23:59:05  [32mCompleted successfully[0m
[2025-06-25T01:59:05.737+0200] {subprocess.py:93} INFO - [0m23:59:05
[2025-06-25T01:59:05.740+0200] {subprocess.py:93} INFO - [0m23:59:05  Done. PASS=4 WARN=0 ERROR=0 SKIP=0 NO-OP=0 TOTAL=4
[2025-06-25T01:59:06.511+0200] {subprocess.py:97} INFO - Command exited with return code 0
[2025-06-25T01:59:06.594+0200] {taskinstance.py:1345} INFO - Marking task as SUCCESS. dag_id=order_monitoring_dag16, task_id=run_dbt_models, execution_date=20250624T235833, start_date=20250624T235844, end_date=20250624T235906
[2025-06-25T01:59:06.661+0200] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2025-06-25T01:59:06.698+0200] {taskinstance.py:2651} INFO - 1 downstream tasks scheduled from follow-on schedule check
