[2025-06-25T02:00:09.392+0200] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: order_monitoring_dag16.run_dbt_models scheduled__2025-06-24T23:00:00+00:00 [queued]>
[2025-06-25T02:00:09.419+0200] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: order_monitoring_dag16.run_dbt_models scheduled__2025-06-24T23:00:00+00:00 [queued]>
[2025-06-25T02:00:09.423+0200] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2025-06-25T02:00:09.490+0200] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): run_dbt_models> on 2025-06-24 23:00:00+00:00
[2025-06-25T02:00:09.500+0200] {standard_task_runner.py:57} INFO - Started process 193128 to run task
[2025-06-25T02:00:09.561+0200] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'order_monitoring_dag16', 'run_dbt_models', 'scheduled__2025-06-24T23:00:00+00:00', '--job-id', '16', '--raw', '--subdir', 'DAGS_FOLDER/order_monitoring_dag.py', '--cfg-path', '/tmp/tmptop77d2g']
[2025-06-25T02:00:09.574+0200] {standard_task_runner.py:85} INFO - Job 16: Subtask run_dbt_models
[2025-06-25T02:00:09.804+0200] {task_command.py:410} INFO - Running <TaskInstance: order_monitoring_dag16.run_dbt_models scheduled__2025-06-24T23:00:00+00:00 [running]> on host 192.168.152.131
[2025-06-25T02:00:10.128+0200] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='imamzafar100@gmail.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='order_monitoring_dag16' AIRFLOW_CTX_TASK_ID='run_dbt_models' AIRFLOW_CTX_EXECUTION_DATE='2025-06-24T23:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-06-24T23:00:00+00:00'
[2025-06-25T02:00:10.135+0200] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2025-06-25T02:00:10.152+0200] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'source "/home/atef/dbt_env/bin/activate" && cd "/home/atef/project/E-Commerce-Order-Pipeline/dbt_ecommerce" && dbt run']
[2025-06-25T02:00:10.205+0200] {subprocess.py:86} INFO - Output:
[2025-06-25T02:00:14.540+0200] {subprocess.py:93} INFO - /home/atef/dbt_env/lib64/python3.9/site-packages/networkx/utils/backends.py:135: RuntimeWarning: networkx backend defined more than once: nx-loopback
[2025-06-25T02:00:14.541+0200] {subprocess.py:93} INFO -   backends.update(_get_backends("networkx.backends"))
[2025-06-25T02:00:16.340+0200] {subprocess.py:93} INFO - [0m00:00:16  Running with dbt=1.10.2
[2025-06-25T02:00:18.286+0200] {subprocess.py:93} INFO - [0m00:00:18  Registered adapter: snowflake=1.9.4
[2025-06-25T02:00:20.232+0200] {subprocess.py:93} INFO - [0m00:00:20  Found 4 models, 476 macros
[2025-06-25T02:00:20.253+0200] {subprocess.py:93} INFO - [0m00:00:20
[2025-06-25T02:00:20.268+0200] {subprocess.py:93} INFO - [0m00:00:20  Concurrency: 1 threads (target='dev')
[2025-06-25T02:00:20.275+0200] {subprocess.py:93} INFO - [0m00:00:20
[2025-06-25T02:00:23.029+0200] {subprocess.py:93} INFO - [0m00:00:23  1 of 4 START sql view model ANALYTICS.stg_customers ............................ [RUN]
[2025-06-25T02:00:23.632+0200] {subprocess.py:93} INFO - [0m00:00:23  1 of 4 OK created sql view model ANALYTICS.stg_customers ....................... [[32mSUCCESS 1[0m in 0.60s]
[2025-06-25T02:00:23.641+0200] {subprocess.py:93} INFO - [0m00:00:23  2 of 4 START sql view model ANALYTICS.stg_orders ............................... [RUN]
[2025-06-25T02:00:24.169+0200] {subprocess.py:93} INFO - [0m00:00:24  2 of 4 OK created sql view model ANALYTICS.stg_orders .......................... [[32mSUCCESS 1[0m in 0.52s]
[2025-06-25T02:00:24.177+0200] {subprocess.py:93} INFO - [0m00:00:24  3 of 4 START sql view model ANALYTICS.stg_shipments ............................ [RUN]
[2025-06-25T02:00:24.546+0200] {subprocess.py:93} INFO - [0m00:00:24  3 of 4 OK created sql view model ANALYTICS.stg_shipments ....................... [[32mSUCCESS 1[0m in 0.36s]
[2025-06-25T02:00:24.555+0200] {subprocess.py:93} INFO - [0m00:00:24  4 of 4 START sql view model ANALYTICS.order_status ............................. [RUN]
[2025-06-25T02:00:25.072+0200] {subprocess.py:93} INFO - [0m00:00:25  4 of 4 OK created sql view model ANALYTICS.order_status ........................ [[32mSUCCESS 1[0m in 0.51s]
[2025-06-25T02:00:25.831+0200] {subprocess.py:93} INFO - [0m00:00:25
[2025-06-25T02:00:25.833+0200] {subprocess.py:93} INFO - [0m00:00:25  Finished running 4 view models in 0 hours 0 minutes and 5.55 seconds (5.55s).
[2025-06-25T02:00:26.062+0200] {subprocess.py:93} INFO - [0m00:00:26
[2025-06-25T02:00:26.064+0200] {subprocess.py:93} INFO - [0m00:00:26  [32mCompleted successfully[0m
[2025-06-25T02:00:26.067+0200] {subprocess.py:93} INFO - [0m00:00:26
[2025-06-25T02:00:26.069+0200] {subprocess.py:93} INFO - [0m00:00:26  Done. PASS=4 WARN=0 ERROR=0 SKIP=0 NO-OP=0 TOTAL=4
[2025-06-25T02:00:26.742+0200] {subprocess.py:97} INFO - Command exited with return code 0
[2025-06-25T02:00:26.856+0200] {taskinstance.py:1345} INFO - Marking task as SUCCESS. dag_id=order_monitoring_dag16, task_id=run_dbt_models, execution_date=20250624T230000, start_date=20250625T000009, end_date=20250625T000026
[2025-06-25T02:00:26.919+0200] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2025-06-25T02:00:26.967+0200] {taskinstance.py:2651} INFO - 1 downstream tasks scheduled from follow-on schedule check
