[2025-06-25T12:06:43.899+0200] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: order_monitoring_dag16.run_dbt_models manual__2025-06-25T10:06:34.932176+00:00 [queued]>
[2025-06-25T12:06:43.909+0200] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: order_monitoring_dag16.run_dbt_models manual__2025-06-25T10:06:34.932176+00:00 [queued]>
[2025-06-25T12:06:43.910+0200] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2025-06-25T12:06:43.939+0200] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): run_dbt_models> on 2025-06-25 10:06:34.932176+00:00
[2025-06-25T12:06:43.945+0200] {standard_task_runner.py:57} INFO - Started process 238926 to run task
[2025-06-25T12:06:43.977+0200] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'order_monitoring_dag16', 'run_dbt_models', 'manual__2025-06-25T10:06:34.932176+00:00', '--job-id', '57', '--raw', '--subdir', 'DAGS_FOLDER/order_monitoring_dag.py', '--cfg-path', '/tmp/tmpi04uv1uv']
[2025-06-25T12:06:43.985+0200] {standard_task_runner.py:85} INFO - Job 57: Subtask run_dbt_models
[2025-06-25T12:06:44.105+0200] {task_command.py:410} INFO - Running <TaskInstance: order_monitoring_dag16.run_dbt_models manual__2025-06-25T10:06:34.932176+00:00 [running]> on host 192.168.152.131
[2025-06-25T12:06:44.211+0200] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='atefatef648@gmail.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='order_monitoring_dag16' AIRFLOW_CTX_TASK_ID='run_dbt_models' AIRFLOW_CTX_EXECUTION_DATE='2025-06-25T10:06:34.932176+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-25T10:06:34.932176+00:00'
[2025-06-25T12:06:44.215+0200] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2025-06-25T12:06:44.217+0200] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'source "/home/atef/dbt_env/bin/activate" && cd "/home/atef/project/E-Commerce-Order-Pipeline/dbt_ecommerce" && dbt run']
[2025-06-25T12:06:44.531+0200] {subprocess.py:86} INFO - Output:
[2025-06-25T12:06:47.618+0200] {subprocess.py:93} INFO - /home/atef/dbt_env/lib64/python3.9/site-packages/networkx/utils/backends.py:135: RuntimeWarning: networkx backend defined more than once: nx-loopback
[2025-06-25T12:06:47.618+0200] {subprocess.py:93} INFO -   backends.update(_get_backends("networkx.backends"))
[2025-06-25T12:06:48.820+0200] {subprocess.py:93} INFO - [0m10:06:48  Running with dbt=1.10.2
[2025-06-25T12:06:50.241+0200] {subprocess.py:93} INFO - [0m10:06:50  Registered adapter: snowflake=1.9.4
[2025-06-25T12:06:52.169+0200] {subprocess.py:93} INFO - [0m10:06:52  Found 4 models, 476 macros
[2025-06-25T12:06:52.174+0200] {subprocess.py:93} INFO - [0m10:06:52
[2025-06-25T12:06:52.176+0200] {subprocess.py:93} INFO - [0m10:06:52  Concurrency: 1 threads (target='dev')
[2025-06-25T12:06:52.178+0200] {subprocess.py:93} INFO - [0m10:06:52
[2025-06-25T12:06:55.337+0200] {subprocess.py:93} INFO - [0m10:06:55  1 of 4 START sql view model ANALYTICS.stg_customers ............................ [RUN]
[2025-06-25T12:06:55.993+0200] {subprocess.py:93} INFO - [0m10:06:55  1 of 4 OK created sql view model ANALYTICS.stg_customers ....................... [[32mSUCCESS 1[0m in 0.64s]
[2025-06-25T12:06:56.001+0200] {subprocess.py:93} INFO - [0m10:06:56  2 of 4 START sql view model ANALYTICS.stg_orders ............................... [RUN]
[2025-06-25T12:06:56.375+0200] {subprocess.py:93} INFO - [0m10:06:56  2 of 4 OK created sql view model ANALYTICS.stg_orders .......................... [[32mSUCCESS 1[0m in 0.37s]
[2025-06-25T12:06:56.389+0200] {subprocess.py:93} INFO - [0m10:06:56  3 of 4 START sql view model ANALYTICS.stg_shipments ............................ [RUN]
[2025-06-25T12:06:56.795+0200] {subprocess.py:93} INFO - [0m10:06:56  3 of 4 OK created sql view model ANALYTICS.stg_shipments ....................... [[32mSUCCESS 1[0m in 0.40s]
[2025-06-25T12:06:56.804+0200] {subprocess.py:93} INFO - [0m10:06:56  4 of 4 START sql view model ANALYTICS.order_status ............................. [RUN]
[2025-06-25T12:06:57.338+0200] {subprocess.py:93} INFO - [0m10:06:57  4 of 4 OK created sql view model ANALYTICS.order_status ........................ [[32mSUCCESS 1[0m in 0.53s]
[2025-06-25T12:06:58.043+0200] {subprocess.py:93} INFO - [0m10:06:58
[2025-06-25T12:06:58.050+0200] {subprocess.py:93} INFO - [0m10:06:58  Finished running 4 view models in 0 hours 0 minutes and 5.86 seconds (5.86s).
[2025-06-25T12:06:58.277+0200] {subprocess.py:93} INFO - [0m10:06:58
[2025-06-25T12:06:58.283+0200] {subprocess.py:93} INFO - [0m10:06:58  [32mCompleted successfully[0m
[2025-06-25T12:06:58.291+0200] {subprocess.py:93} INFO - [0m10:06:58
[2025-06-25T12:06:58.293+0200] {subprocess.py:93} INFO - [0m10:06:58  Done. PASS=4 WARN=0 ERROR=0 SKIP=0 NO-OP=0 TOTAL=4
[2025-06-25T12:06:59.087+0200] {subprocess.py:97} INFO - Command exited with return code 0
[2025-06-25T12:06:59.206+0200] {taskinstance.py:1345} INFO - Marking task as SUCCESS. dag_id=order_monitoring_dag16, task_id=run_dbt_models, execution_date=20250625T100634, start_date=20250625T100643, end_date=20250625T100659
[2025-06-25T12:06:59.283+0200] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2025-06-25T12:06:59.342+0200] {taskinstance.py:2651} INFO - 1 downstream tasks scheduled from follow-on schedule check
