[2025-06-25T08:35:31.986+0200] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: order_monitoring_dag16.run_dbt_models scheduled__2025-06-25T01:00:00+00:00 [queued]>
[2025-06-25T08:35:31.994+0200] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: order_monitoring_dag16.run_dbt_models scheduled__2025-06-25T01:00:00+00:00 [queued]>
[2025-06-25T08:35:31.994+0200] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2025-06-25T08:35:32.021+0200] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): run_dbt_models> on 2025-06-25 01:00:00+00:00
[2025-06-25T08:35:32.030+0200] {standard_task_runner.py:57} INFO - Started process 208667 to run task
[2025-06-25T08:35:32.269+0200] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'order_monitoring_dag16', 'run_dbt_models', 'scheduled__2025-06-25T01:00:00+00:00', '--job-id', '20', '--raw', '--subdir', 'DAGS_FOLDER/order_monitoring_dag.py', '--cfg-path', '/tmp/tmpk1jfnlu3']
[2025-06-25T08:35:32.340+0200] {standard_task_runner.py:85} INFO - Job 20: Subtask run_dbt_models
[2025-06-25T08:35:34.446+0200] {task_command.py:410} INFO - Running <TaskInstance: order_monitoring_dag16.run_dbt_models scheduled__2025-06-25T01:00:00+00:00 [running]> on host 192.168.152.131
[2025-06-25T08:35:35.582+0200] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='imamzafar100@gmail.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='order_monitoring_dag16' AIRFLOW_CTX_TASK_ID='run_dbt_models' AIRFLOW_CTX_EXECUTION_DATE='2025-06-25T01:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-06-25T01:00:00+00:00'
[2025-06-25T08:35:35.587+0200] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2025-06-25T08:35:35.589+0200] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'source "/home/atef/dbt_env/bin/activate" && cd "/home/atef/project/E-Commerce-Order-Pipeline/dbt_ecommerce" && dbt run']
[2025-06-25T08:35:35.974+0200] {subprocess.py:86} INFO - Output:
[2025-06-25T08:35:40.967+0200] {subprocess.py:93} INFO - /home/atef/dbt_env/lib64/python3.9/site-packages/networkx/utils/backends.py:135: RuntimeWarning: networkx backend defined more than once: nx-loopback
[2025-06-25T08:35:40.967+0200] {subprocess.py:93} INFO -   backends.update(_get_backends("networkx.backends"))
[2025-06-25T08:35:42.435+0200] {subprocess.py:93} INFO - [0m06:35:42  Running with dbt=1.10.2
[2025-06-25T08:35:44.930+0200] {subprocess.py:93} INFO - [0m06:35:44  Registered adapter: snowflake=1.9.4
[2025-06-25T08:35:46.692+0200] {subprocess.py:93} INFO - [0m06:35:46  Found 4 models, 476 macros
[2025-06-25T08:35:46.703+0200] {subprocess.py:93} INFO - [0m06:35:46
[2025-06-25T08:35:46.705+0200] {subprocess.py:93} INFO - [0m06:35:46  Concurrency: 1 threads (target='dev')
[2025-06-25T08:35:46.706+0200] {subprocess.py:93} INFO - [0m06:35:46
[2025-06-25T08:35:50.330+0200] {subprocess.py:93} INFO - [0m06:35:50  1 of 4 START sql view model ANALYTICS.stg_customers ............................ [RUN]
[2025-06-25T08:35:51.019+0200] {subprocess.py:93} INFO - [0m06:35:51  1 of 4 OK created sql view model ANALYTICS.stg_customers ....................... [[32mSUCCESS 1[0m in 0.68s]
[2025-06-25T08:35:51.028+0200] {subprocess.py:93} INFO - [0m06:35:51  2 of 4 START sql view model ANALYTICS.stg_orders ............................... [RUN]
[2025-06-25T08:35:51.419+0200] {subprocess.py:93} INFO - [0m06:35:51  2 of 4 OK created sql view model ANALYTICS.stg_orders .......................... [[32mSUCCESS 1[0m in 0.39s]
[2025-06-25T08:35:51.424+0200] {subprocess.py:93} INFO - [0m06:35:51  3 of 4 START sql view model ANALYTICS.stg_shipments ............................ [RUN]
[2025-06-25T08:35:51.804+0200] {subprocess.py:93} INFO - [0m06:35:51  3 of 4 OK created sql view model ANALYTICS.stg_shipments ....................... [[32mSUCCESS 1[0m in 0.38s]
[2025-06-25T08:35:51.810+0200] {subprocess.py:93} INFO - [0m06:35:51  4 of 4 START sql view model ANALYTICS.order_status ............................. [RUN]
[2025-06-25T08:35:52.384+0200] {subprocess.py:93} INFO - [0m06:35:52  4 of 4 OK created sql view model ANALYTICS.order_status ........................ [[32mSUCCESS 1[0m in 0.57s]
[2025-06-25T08:35:53.098+0200] {subprocess.py:93} INFO - [0m06:35:53
[2025-06-25T08:35:53.100+0200] {subprocess.py:93} INFO - [0m06:35:53  Finished running 4 view models in 0 hours 0 minutes and 6.39 seconds (6.39s).
[2025-06-25T08:35:53.190+0200] {subprocess.py:93} INFO - [0m06:35:53
[2025-06-25T08:35:53.192+0200] {subprocess.py:93} INFO - [0m06:35:53  [32mCompleted successfully[0m
[2025-06-25T08:35:53.194+0200] {subprocess.py:93} INFO - [0m06:35:53
[2025-06-25T08:35:53.195+0200] {subprocess.py:93} INFO - [0m06:35:53  Done. PASS=4 WARN=0 ERROR=0 SKIP=0 NO-OP=0 TOTAL=4
[2025-06-25T08:35:53.778+0200] {subprocess.py:97} INFO - Command exited with return code 0
[2025-06-25T08:35:53.886+0200] {taskinstance.py:1345} INFO - Marking task as SUCCESS. dag_id=order_monitoring_dag16, task_id=run_dbt_models, execution_date=20250625T010000, start_date=20250625T063531, end_date=20250625T063553
[2025-06-25T08:35:53.952+0200] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2025-06-25T08:35:53.989+0200] {taskinstance.py:2651} INFO - 1 downstream tasks scheduled from follow-on schedule check
