[2025-06-25T08:35:59.891+0200] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: order_monitoring_dag16.run_dbt_models scheduled__2025-06-25T05:00:00+00:00 [queued]>
[2025-06-25T08:35:59.899+0200] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: order_monitoring_dag16.run_dbt_models scheduled__2025-06-25T05:00:00+00:00 [queued]>
[2025-06-25T08:35:59.900+0200] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2025-06-25T08:35:59.933+0200] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): run_dbt_models> on 2025-06-25 05:00:00+00:00
[2025-06-25T08:35:59.939+0200] {standard_task_runner.py:57} INFO - Started process 208942 to run task
[2025-06-25T08:35:59.990+0200] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'order_monitoring_dag16', 'run_dbt_models', 'scheduled__2025-06-25T05:00:00+00:00', '--job-id', '21', '--raw', '--subdir', 'DAGS_FOLDER/order_monitoring_dag.py', '--cfg-path', '/tmp/tmpn4z8depq']
[2025-06-25T08:35:59.998+0200] {standard_task_runner.py:85} INFO - Job 21: Subtask run_dbt_models
[2025-06-25T08:36:00.114+0200] {task_command.py:410} INFO - Running <TaskInstance: order_monitoring_dag16.run_dbt_models scheduled__2025-06-25T05:00:00+00:00 [running]> on host 192.168.152.131
[2025-06-25T08:36:00.227+0200] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='imamzafar100@gmail.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='order_monitoring_dag16' AIRFLOW_CTX_TASK_ID='run_dbt_models' AIRFLOW_CTX_EXECUTION_DATE='2025-06-25T05:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-06-25T05:00:00+00:00'
[2025-06-25T08:36:00.233+0200] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2025-06-25T08:36:00.235+0200] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'source "/home/atef/dbt_env/bin/activate" && cd "/home/atef/project/E-Commerce-Order-Pipeline/dbt_ecommerce" && dbt run']
[2025-06-25T08:36:00.256+0200] {subprocess.py:86} INFO - Output:
[2025-06-25T08:36:03.483+0200] {subprocess.py:93} INFO - /home/atef/dbt_env/lib64/python3.9/site-packages/networkx/utils/backends.py:135: RuntimeWarning: networkx backend defined more than once: nx-loopback
[2025-06-25T08:36:03.484+0200] {subprocess.py:93} INFO -   backends.update(_get_backends("networkx.backends"))
[2025-06-25T08:36:04.250+0200] {subprocess.py:93} INFO - [0m06:36:04  Running with dbt=1.10.2
[2025-06-25T08:36:05.539+0200] {subprocess.py:93} INFO - [0m06:36:05  Registered adapter: snowflake=1.9.4
[2025-06-25T08:36:07.436+0200] {subprocess.py:93} INFO - [0m06:36:07  Found 4 models, 476 macros
[2025-06-25T08:36:07.441+0200] {subprocess.py:93} INFO - [0m06:36:07
[2025-06-25T08:36:07.443+0200] {subprocess.py:93} INFO - [0m06:36:07  Concurrency: 1 threads (target='dev')
[2025-06-25T08:36:07.445+0200] {subprocess.py:93} INFO - [0m06:36:07
[2025-06-25T08:36:10.295+0200] {subprocess.py:93} INFO - [0m06:36:10  1 of 4 START sql view model ANALYTICS.stg_customers ............................ [RUN]
[2025-06-25T08:36:11.077+0200] {subprocess.py:93} INFO - [0m06:36:11  1 of 4 OK created sql view model ANALYTICS.stg_customers ....................... [[32mSUCCESS 1[0m in 0.78s]
[2025-06-25T08:36:11.081+0200] {subprocess.py:93} INFO - [0m06:36:11  2 of 4 START sql view model ANALYTICS.stg_orders ............................... [RUN]
[2025-06-25T08:36:11.430+0200] {subprocess.py:93} INFO - [0m06:36:11  2 of 4 OK created sql view model ANALYTICS.stg_orders .......................... [[32mSUCCESS 1[0m in 0.34s]
[2025-06-25T08:36:11.439+0200] {subprocess.py:93} INFO - [0m06:36:11  3 of 4 START sql view model ANALYTICS.stg_shipments ............................ [RUN]
[2025-06-25T08:36:11.798+0200] {subprocess.py:93} INFO - [0m06:36:11  3 of 4 OK created sql view model ANALYTICS.stg_shipments ....................... [[32mSUCCESS 1[0m in 0.36s]
[2025-06-25T08:36:11.805+0200] {subprocess.py:93} INFO - [0m06:36:11  4 of 4 START sql view model ANALYTICS.order_status ............................. [RUN]
[2025-06-25T08:36:12.322+0200] {subprocess.py:93} INFO - [0m06:36:12  4 of 4 OK created sql view model ANALYTICS.order_status ........................ [[32mSUCCESS 1[0m in 0.51s]
[2025-06-25T08:36:13.141+0200] {subprocess.py:93} INFO - [0m06:36:13
[2025-06-25T08:36:13.143+0200] {subprocess.py:93} INFO - [0m06:36:13  Finished running 4 view models in 0 hours 0 minutes and 5.69 seconds (5.69s).
[2025-06-25T08:36:13.224+0200] {subprocess.py:93} INFO - [0m06:36:13
[2025-06-25T08:36:13.226+0200] {subprocess.py:93} INFO - [0m06:36:13  [32mCompleted successfully[0m
[2025-06-25T08:36:13.228+0200] {subprocess.py:93} INFO - [0m06:36:13
[2025-06-25T08:36:13.230+0200] {subprocess.py:93} INFO - [0m06:36:13  Done. PASS=4 WARN=0 ERROR=0 SKIP=0 NO-OP=0 TOTAL=4
[2025-06-25T08:36:13.678+0200] {subprocess.py:97} INFO - Command exited with return code 0
[2025-06-25T08:36:13.749+0200] {taskinstance.py:1345} INFO - Marking task as SUCCESS. dag_id=order_monitoring_dag16, task_id=run_dbt_models, execution_date=20250625T050000, start_date=20250625T063559, end_date=20250625T063613
[2025-06-25T08:36:13.823+0200] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2025-06-25T08:36:13.883+0200] {taskinstance.py:2651} INFO - 1 downstream tasks scheduled from follow-on schedule check
