[2025-06-25T03:00:09.000+0200] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: order_monitoring_dag16.run_dbt_models scheduled__2025-06-25T00:00:00+00:00 [queued]>
[2025-06-25T03:00:09.014+0200] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: order_monitoring_dag16.run_dbt_models scheduled__2025-06-25T00:00:00+00:00 [queued]>
[2025-06-25T03:00:09.014+0200] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2025-06-25T03:00:09.072+0200] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): run_dbt_models> on 2025-06-25 00:00:00+00:00
[2025-06-25T03:00:09.081+0200] {standard_task_runner.py:57} INFO - Started process 202977 to run task
[2025-06-25T03:00:09.128+0200] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'order_monitoring_dag16', 'run_dbt_models', 'scheduled__2025-06-25T00:00:00+00:00', '--job-id', '18', '--raw', '--subdir', 'DAGS_FOLDER/order_monitoring_dag.py', '--cfg-path', '/tmp/tmp4324sjyi']
[2025-06-25T03:00:09.140+0200] {standard_task_runner.py:85} INFO - Job 18: Subtask run_dbt_models
[2025-06-25T03:00:09.313+0200] {task_command.py:410} INFO - Running <TaskInstance: order_monitoring_dag16.run_dbt_models scheduled__2025-06-25T00:00:00+00:00 [running]> on host 192.168.152.131
[2025-06-25T03:00:09.410+0200] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='imamzafar100@gmail.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='order_monitoring_dag16' AIRFLOW_CTX_TASK_ID='run_dbt_models' AIRFLOW_CTX_EXECUTION_DATE='2025-06-25T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-06-25T00:00:00+00:00'
[2025-06-25T03:00:09.414+0200] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2025-06-25T03:00:09.416+0200] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'source "/home/atef/dbt_env/bin/activate" && cd "/home/atef/project/E-Commerce-Order-Pipeline/dbt_ecommerce" && dbt run']
[2025-06-25T03:00:09.479+0200] {subprocess.py:86} INFO - Output:
[2025-06-25T03:00:12.192+0200] {subprocess.py:93} INFO - /home/atef/dbt_env/lib64/python3.9/site-packages/networkx/utils/backends.py:135: RuntimeWarning: networkx backend defined more than once: nx-loopback
[2025-06-25T03:00:12.192+0200] {subprocess.py:93} INFO -   backends.update(_get_backends("networkx.backends"))
[2025-06-25T03:00:12.939+0200] {subprocess.py:93} INFO - [0m01:00:12  Running with dbt=1.10.2
[2025-06-25T03:00:14.597+0200] {subprocess.py:93} INFO - [0m01:00:14  Registered adapter: snowflake=1.9.4
[2025-06-25T03:00:16.246+0200] {subprocess.py:93} INFO - [0m01:00:16  Found 4 models, 476 macros
[2025-06-25T03:00:16.252+0200] {subprocess.py:93} INFO - [0m01:00:16
[2025-06-25T03:00:16.254+0200] {subprocess.py:93} INFO - [0m01:00:16  Concurrency: 1 threads (target='dev')
[2025-06-25T03:00:16.255+0200] {subprocess.py:93} INFO - [0m01:00:16
[2025-06-25T03:00:19.107+0200] {subprocess.py:93} INFO - [0m01:00:19  1 of 4 START sql view model ANALYTICS.stg_customers ............................ [RUN]
[2025-06-25T03:00:19.730+0200] {subprocess.py:93} INFO - [0m01:00:19  1 of 4 OK created sql view model ANALYTICS.stg_customers ....................... [[32mSUCCESS 1[0m in 0.62s]
[2025-06-25T03:00:19.734+0200] {subprocess.py:93} INFO - [0m01:00:19  2 of 4 START sql view model ANALYTICS.stg_orders ............................... [RUN]
[2025-06-25T03:00:20.047+0200] {subprocess.py:93} INFO - [0m01:00:20  2 of 4 OK created sql view model ANALYTICS.stg_orders .......................... [[32mSUCCESS 1[0m in 0.31s]
[2025-06-25T03:00:20.051+0200] {subprocess.py:93} INFO - [0m01:00:20  3 of 4 START sql view model ANALYTICS.stg_shipments ............................ [RUN]
[2025-06-25T03:00:20.411+0200] {subprocess.py:93} INFO - [0m01:00:20  3 of 4 OK created sql view model ANALYTICS.stg_shipments ....................... [[32mSUCCESS 1[0m in 0.36s]
[2025-06-25T03:00:20.416+0200] {subprocess.py:93} INFO - [0m01:00:20  4 of 4 START sql view model ANALYTICS.order_status ............................. [RUN]
[2025-06-25T03:00:20.911+0200] {subprocess.py:93} INFO - [0m01:00:20  4 of 4 OK created sql view model ANALYTICS.order_status ........................ [[32mSUCCESS 1[0m in 0.49s]
[2025-06-25T03:00:21.656+0200] {subprocess.py:93} INFO - [0m01:00:21
[2025-06-25T03:00:21.657+0200] {subprocess.py:93} INFO - [0m01:00:21  Finished running 4 view models in 0 hours 0 minutes and 5.40 seconds (5.40s).
[2025-06-25T03:00:21.732+0200] {subprocess.py:93} INFO - [0m01:00:21
[2025-06-25T03:00:21.733+0200] {subprocess.py:93} INFO - [0m01:00:21  [32mCompleted successfully[0m
[2025-06-25T03:00:21.734+0200] {subprocess.py:93} INFO - [0m01:00:21
[2025-06-25T03:00:21.736+0200] {subprocess.py:93} INFO - [0m01:00:21  Done. PASS=4 WARN=0 ERROR=0 SKIP=0 NO-OP=0 TOTAL=4
[2025-06-25T03:00:22.196+0200] {subprocess.py:97} INFO - Command exited with return code 0
[2025-06-25T03:00:22.349+0200] {taskinstance.py:1345} INFO - Marking task as SUCCESS. dag_id=order_monitoring_dag16, task_id=run_dbt_models, execution_date=20250625T000000, start_date=20250625T010009, end_date=20250625T010022
[2025-06-25T03:00:22.477+0200] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2025-06-25T03:00:22.605+0200] {taskinstance.py:2651} INFO - 1 downstream tasks scheduled from follow-on schedule check
